# Generated by Django 5.2.1 on 2025-05-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('profile_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='tagging.profileb')),
            ],
        ),
        migrations.CreateModel(
            name='TagExplicit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.profilea')),
                ('profile_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.profileb')),
                ('profile_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.profilec')),
                ('profile_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.profiled')),
            ],
        ),
        migrations.CreateModel(
            name='TagGFK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tagging_tag_content_bf5017_idx')],
            },
        ),
    ]
